# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mailee}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Juan Maiz"]
  s.date = %q{2010-10-07}
  s.description = %q{Permite sincronizar automaticamente seus modelos com o Mailee.me, inclusive com gerenciamento de optin.}
  s.email = %q{suporte@mailee.me}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "MIT-LICENSE",
     "README.markdown",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/mailee.rb",
     "mailee.gemspec",
     "pkg/mailee-0.1.0.gem",
     "pkg/mailee-0.1.1.gem",
     "pkg/mailee-0.1.2.gem",
     "spec/ar_spec_helper.rb",
     "spec/mailee-api-ar.rb",
     "spec/mailee-api.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/mailee_tasks.rake"
  ]
  s.homepage = %q{http://help.mailee.me/integration_rails.html}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gem de integração do Mailee.me}
  s.test_files = [
    "spec/ar_spec_helper.rb",
     "spec/mailee-api-ar.rb",
     "spec/mailee-api.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

